### ISSUE TITLE
Polyfill does not support videos with a MediaStream source in Firefox

### ISSUE THREAD

**Issue by tanyagray** [ThaUnknown/rvfc-polyfill#1]
In Firefox (v102.0.1 64-bit, macOS Monterey), when the video element is streaming a WebRTC video, the `mozPresentedFrames` value is always zero.

WebRTC still uses `mozPaintedFrames` and has not migrated to `mozPresentedFrames` (or so it seems, according to very old threads like [this one](https://bugzilla.mozilla.org/show_bug.cgi?id=1379050)

**Changing `mozPresentedFrames` to `mozPaintedFrames` in this polyfill will make it work with a WebRTC source.**

However, the above is not a "fix" as it will only cater to WebRTC, so I have not submitted a PR. `mozPresentedFrames` is the correct value to use, and it is the WebRTC implementation that appears to not be using the correct property.

Hopefully this will help someone else and/or someone may know a way to support both cases intelligently 🤞

**Comment by ThaUnknown** [comment]
mind making a test case for me?

**Comment by ThaUnknown** [comment]
wew, this is very scuffed, as expected of firefox, TLDR ANYTHING except `mozPaintedFrames` will report 0, even standardized API's like getvideoplaybackquality, good stuff

> `mozPresentedFrames` is the correct value to use

actually this is debatable af, as this uses RAF, most other properties will behave the same, I'll test some accuracy with CFR and VFR and fix this
