### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by martenrichter** [ThaUnknown/rvfc-polyfill#2]
Thank you for the polyfill!
But it is missing licensing information, so it is unclear, if it can be used in other projects?
Can you please choose a license?

**Comment by ThaUnknown** [comment]
https://github.com/ThaUnknown/rvfc-polyfill/blob/main/package.json#L7

**Comment by ThaUnknown** [comment]
wait what the fuck happened there, i swear it was MIT

**Comment by martenrichter** [comment]
Yes and I have no idea what GPT-3 is?

**Comment by ThaUnknown** [comment]
> Yes and I have no idea what GPT-3 is?

neither do I XD that package json was autogenerated, I'll fix it up soon-ish

**Comment by ko-synth** [comment]
Hello @ThaUnknown. First of all, thanks for the package!

Is the license gonna change to MIT or are we stuck with the GPL-3?
