### ISSUE TITLE
Does not work on iOS 15.1

### ISSUE THREAD

**Issue by ivancuric** [ThaUnknown/rvfc-polyfill#3]
Tried running on an older iOS device, however the callback never triggers.

**Comment by ThaUnknown** [comment]
I've been told that some browsers don't report `getVideoPlaybackQuality`'s data at all, just yield 0 for everything, there isn't much I can do about this as I can't debug it myself, feel free to try tracking down the issue, the library is fairly simple so it shouldn't be too hard

**Comment by ThaUnknown** [comment]
I won't be fixing this, this isn't reproductible on IOS 16.4.1's Safari, and IOS 15.1 isn't signed anymore as it expired, so you can't install it on new devices, provide reproduction steps if you want this fixed, would be good if you also checked what `getVideoPlaybackQuality` outputs on your end
