### ISSUE TITLE
Support node environments (SSR)

### ISSUE THREAD

**Issue by zoriya** [ThaUnknown/rvfc-polyfill#4]
I wanted to migrate from JSO to Jassub (for [Kyoo](https://github.com/zoriya/kyoo), but this polyfill is always imported, and it does not support SSR (node environments where HTMLVideoElement is not defined) so everything crashes.

**Comment by zoriya** [comment]
Thanks for being so fast, I was not expecting this speed!

**Comment by ThaUnknown** [comment]
anything to stick it to JSO [I'm petty like that]
