### ISSUE TITLE
Incorrect timestamp after seek

### ISSUE THREAD

**Issue by gismya** [ThaUnknown/rvfc-polyfill#5]
The design of the callback, where it predicts the "upcoming" frame, makes it produce incorrect times when seeking during paused playback, instead reporting the time of the upcoming frame.

Title and issue changed after [comment](https://github.com/ThaUnknown/rvfc-polyfill/issues/5#issuecomment-1881251248). Original title and text:

~~Title: Incorrect times in the callback~~
~~Hello!~~

~~Working on a project that uses requestVideoFrameCallback, so I added the polyfill to get Firefox compatibility.
I realized after a while that the values reported in Firefox was one frame higher than the values reported in other browsers, so I started looking at the polyfill code.~~

~~The values that I think are incorrect are:~~
```
        callback(now, {
          presentationTime: now + processingDuration * 1000,
          expectedDisplayTime: now + timediff,
          mediaTime: Math.max(0, this.currentTime || 0) + timediff / 1000,
        });
```
~~Since the frame has already been rendered, and currentTime has already been updated on the video element, this gives a mediaTime and an expectedDisplayTime that's an approximation of the mediaTime for the next frame.~~

~~From what I understand of the available APIs that are being used, the following would be the closest approximation to the correct values for the polyfill:~~

```
        callback(now, {
          presentationTime: now - processingDuration * 1000,
          expectedDisplayTime: now,
          mediaTime: this.currentTime,
        });
```

**Comment by ThaUnknown** [comment]
because of VSync RVFC reports the next frame that's about to be painted according to RAF, it's kinda wonky, but TLDR the callback reports the time of the next RAF

**Comment by ThaUnknown** [comment]
I tested this by syncing a box being drawn together with the video, and it seems roughly accurate https://thaunknown.github.io/jassub/jassub/variable/index.html

**Comment by gismya** [comment]
> because of VSync RVFC reports the next frame that's about to be painted according to RAF, it's kinda wonky, but TLDR the callback reports the time of the next RAF

Isn't that simply because native RVFC can trigger before the rendering, whereas a solution based on RAF can't do that? 

If I have a video that has a rvfc and I seek to a point, the time that the polyfill reports is one frame ahead of the time reported by the native implementations in Chrome and Safari. Is that by design?

**Comment by ThaUnknown** [comment]
> Isn't that simply because native RVFC can trigger before the rendering, whereas a solution based on RAF can't do that?

yup, that sums it up pretty well, RVFC triggers when a video frame is decoded, prepared for paining and or painted, but not visible on the user's screen yet, the polyfill can only detect a frame after it was painted

yeah it's a side effect that I'm unsure if it's even fixable, TLDR this polyfill can't be used for frame perfect video timmings only for "rough when a video frame was painted", if u come up with a fix, feel free to PR

**Comment by gismya** [comment]
Oh, testing with playback instead of seeking I see what you mean. Whereas the polyfill is one frame ahead of the native implementation on seek, my fix is usually (Depending on RAF timing) one frame behind on playback pause.

I'll see if I can come up with a way to square that.

Would it make sense to poll the `paused` property and not add the timediff if it's currently paused to fix the seeking behaviour?

**Comment by ThaUnknown** [comment]
yeah, RVFC is not really something that can be easily polyfilled accurately, which is why it's such a great API, this just somewhat roughly mimics it's behaviour

**Comment by gismya** [comment]
I changed the issue to reflect the actual problem, and I'll see if I can find a way to resolve it and send a PR.

**Comment by gismya** [comment]
No, failed to find a way to make that work reliably resolve that. A note in the readme to the effect of "Since the polyfill is expecting a future frame, it will report a mediaTime that is one frame ahead of the native implementations when seeking in a paused state." might be the best we can do.
